import Ember from 'ember';

const defaultValues = {
  keyEsc: 'cancelselect',
  keyF1: '',
  keyF2: '',
  keyF3: 'autobuy',
  keyF4: 'rebuy',
  keyF5: 'jpeg',
  keyF6: 'save quick',
  keyF7: 'save load',
  keyF8: '',
  keyF9: '',
  keyF10: 'quit prompt',
  keyF11: '',
  keyF12: '',
  keyK1: 'slot1;',
  keyK2: 'slot2;',
  keyK3: 'slot3;',
  keyK4: 'slot4;',
  keyK5: 'slot5;',
  keyK6: 'slot6;',
  keyK7: 'slot7;',
  keyK8: 'slot8;',
  keyK9: 'slot9;',
  keyK0: 'slot10;',
  keyHyphen: '',
  keyEquals: '',
  keyBackspace: '',
  keyTab: '+showscores;',
  keyQ: 'lastinv;',
  keyW: '+forward;',
  keyE: '+use;',
  keyR: '+reload;',
  keyT: '',
  keyY: 'messagemode;',
  keyU: 'messagemode2;',
  keyI: 'show_loadout_toggle;',
  keyO: '',
  keyP: '',
  keyLbracket: '',
  keyRbracket: '',
  keyBkslash: '',
  keyCapslock: '',
  keyA: '+moveleft;',
  keyS: '+back;',
  keyD: '+moveright;',
  keyF: '+lookatweapon;',
  keyG: 'drop;',
  keyH: '',
  keyJ: '',
  keyK: '',
  keyL: '',
  keySemicolon: '',
  keyApostrophe: '',
  keyEnter: '',
  keyShift: '+speed;',
  keyZ: 'radio1;',
  keyX: 'radio2;',
  keyC: 'radio3;',
  keyV: '',
  keyB: 'buymenu;',
  keyN: '',
  keyM: 'teammenu;',
  keyComma: '',
  keyPeriod: '',
  keyFwslash: '',
  keyCtrl: '+duck;',
  keyAlt: '',
  keySpace: '+jump;',
  keyPause: 'pause',
  keyIns: '',
  keyHome: '',
  keyPgup: '',
  keyDel: 'mute',
  keyEnd: '',
  keyPgdn: '',
  keyUparrow: '',
  keyLeftarrow: '',
  keyDownarrow: '',
  keyRightarrow: '',
  keyKpSlash: '',
  keyKpMultiply: '',
  keyKpMinus: '',
  keyKpHome: '',
  keyKpUparrow: '',
  keyKpPgup: '',
  keyKpPlus: '',
  keyKpLeftarrow: '',
  keyKp5: '',
  keyKpRightarrow: '',
  keyKpEnd: '',
  keyKpDownarrow: '',
  keyKpPgdn: '',
  keyKpEnter: '',
  keyKpIns: '',
  keyKpDel: '',
  keyMouse1: '+attack;',
  keyMwheelup: '',
  keyMouse3: '',
  keyMwheeldown: '',
  keyMouse2: '+attack2;',
  keyMouse4: '',
  keyMouse5: '',
};

export default Ember.Component.extend({
  data: defaultValues,
  isOpen: false,
  actions: {
    toggleDisplay() {
      this.toggleProperty('isOpen');
    }
  }
});
